# 01 | Transform the Data

# Introduction
In this notebook, we will deal with the data transformation steps required to proceed with our analysis. This process will be reproduced as .py files later on.

# Goals:
Targeted objectives in this notebook ar checked as follows:

- [ ] Import the raw data
  -  [ ] SIPRI dataset and capitals coordinates
- [ ]  Store the raw data
- [x] Prepare the data
  - [x] Clean each individual table
  - [x] Store the transformed dataset
- [ ] Combine both datasets
  - Check if the merging column values match
- [ ] Store the final output

# Set up our working environment

In [71]:
# Import required libraries
import pandas as pd
import numpy as np
import os
from geopy.distance import geodesic
from tableauhyperapi import (
    HyperProcess,
    Telemetry,
    Connection,
    CreateMode,
    NOT_NULLABLE,
    NULLABLE,
    SqlType,
    TableDefinition,
    Inserter,
    HyperException,
    )

In [72]:
# Create directory folders to store our data
dirname = os.getcwd()

raw_data = f"{dirname}/data/raw/"
transformed_data = f"{dirname}/data/transformed/"
refined_data = f"{dirname}/data/refined/"

paths = [raw_data, transformed_data, refined_data]

for path in paths:
    if not os.path.exists(path):
        os.makedirs(path)

# Data Transformation | SIPRI dataset
Let's start by preparing our main dataset for data analysis.

## Import raw data
We'll first import the raw data that we stored during the previous step. Because we have three indivual tables that must turn into one, we must establish a few steps:
- Import a single table;
- Analyse the required transformation steps we need;
- Apply the transformations;
- Loop through the 3 tables and pass the same steps (if possible);

### Import data
We can start by using table 5 (Constant US$ (2022)).

In [73]:
sipri_raw = sipri_raw = pd.read_csv(f"{raw_data}sipri_data_raw_tb_5.csv")
sipri_raw.head()

,"Military expenditure by country, in millions of US$ at current prices and exchange rates, 1949-2024 © SIPRI 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77
0,"Figures are in US $m., in current prices, conv...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Figures in blue are SIPRI estimates. Figures i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,""". ."" = data unavailable. ""xxx"" = country did ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Country,Notes,1949,1950,1951,1952,1953,1954,1955,1956,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024

**Challenge** – the table contains additional non-tabular information on the first rows. We must remove them. Considering that the number of extra rows may differ between each `.csv` file, we need to dynamically identify what is our header. We need to:
- Read the file.
- Iterate through each line using `enumerate`.
- For each value in each index, if `Country` appears, return the index value `i` and define it as `header_row`
  - It will be used to define the number of rows we need to skip when reading our `.csv` file.

In [74]:
# Read the file in chunks to find the header row
with open(f"{raw_data}sipri_data_raw_tb_5.csv", "r") as file:
    for i, line in enumerate(file):
        if "Country" in line:
            header_row = i # define header if `Country` is a value
            break

In [75]:
sipri_raw_tb5 = pd.read_csv(f"{raw_data}sipri_data_raw_tb_5.csv", skiprows=header_row, header=0)
sipri_raw_tb5.head()

,Country,Notes,1949,1950,1951,1952,1953,1954,1955,1956,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,North Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Algeria,§4,...,...,...,...,...,...,...,...,...,10407.345244361462,10217.081699569308,10073.364021301344,9583.7242883703,10303.60057521065,9708.277440227255,9112.461105348943,9145.810174207281,18263.96796826213,21811.24255503127
4,Libya,‡§¶16,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,1214.8645582452625,1573.6827773146888,...

In [76]:
sipri_raw_tb5.tail()

,Country,Notes,1949,1950,1951,1952,1953,1954,1955,1956,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
188,Syria,§,...,...,...,...,...,...,...,55.58659217877095,...,...,...,...,...,...,...,...,...,...,...
189,Türkiye,‖,197.68186020052622,212.97020550380432,231.81397994737964,257.7686126715495,294.0339899025812,332.0770817037616,382.9197184100121,412.07423736044944,...,15668.749999999998,17827.702150796664,17822.738263164494,19648.69382385138,20436.917121238785,15782.990905830842,15254.829834666363,15036.835693606365,19577.831923543665,24978.735534603824
190,United Arab Emirates,§98,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,"Yemen, North",§100,...,...,...,...,...,...,...,...,...,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx
192,Yemen,§99,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

Great! Now, we can take a brief look at the structure of our dataset.

In [77]:
sipri_raw_tb5.shape

(193, 78)

In [78]:
sipri_raw_tb5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 78 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  192 non-null    object
 1   Notes    136 non-null    object
 2   1949     174 non-null    object
 3   1950     174 non-null    object
 4   1951     174 non-null    object
 5   1952     174 non-null    object
 6   1953     174 non-null    object
 7   1954     174 non-null    object
 8   1955     174 non-null    object
 9   1956     174 non-null    object
 10  1957     174 non-null    object
 11  1958     174 non-null    object
 12  1959     174 non-null    object
 13  1960     174 non-null    object
 14  1961     174 non-null    object
 15  1962     174 non-null    object
 16  1963     174 non-null    object
 17  1964     174 non-null    object
 18  1965     174 non-null    object
 19  1966     174 non-null    object
 20  1967     174 non-null    object
 21  1968     174 non-null    object
 22  1969     174 non-null    object
 23  1970     174 non-null    object
 24  1971     174 non-null    object
 25  1972     174 non-null    object
 26  1973     174 non-null    object
 27  1974     174 non-null    object
 28  1975     174 non-null    object
 29  1976     174 non-null    object
 30  1977     174 non-null    object
 31  1978     174 non-null    object
 32  1979     174 non-null    object
 33  1980     174 non-null    object
 34  1981     174 non-null    object
 35  1982     174 non-null    object
 36  1983     174 non-null    object
 37  1984     174 non-null    object
 38  1985     174 non-null    object
 39  1986     174 non-null    object
 40  1987     174 non-null    object
 41  1988     174 non-null    object
 42  1989     174 non-null    object
 43  1990     174 non-null    object
 44  1991     174 non-null    object
 45  1992     174 non-null    object
 46  1993     174 non-null    object
 47  1994     174 non-null    object
 48  1995     174 non-null    object
 49  1996     174 non-null    object
 50  1997     174 non-null    object
 51  1998     174 non-null    object
 52  1999     174 non-null    object
 53  2000     174 non-null    object
 54  2001     174 non-null    object
 55  2002     174 non-null    object
 56  2003     174 non-null    object
 57  2004     174 non-null    object
 58  2005     174 non-null    object
 59  2006     174 non-null    object
 60  2007     174 non-null    object
 61  2008     174 non-null    object
 62  2009     174 non-null    object
 63  2010     174 non-null    object
 64  2011     174 non-null    object
 65  2012     174 non-null    object
 66  2013     174 non-null    object
 67  2014     174 non-null    object
 68  2015     174 non-null    object
 69  2016     174 non-null    object
 70  2017     174 non-null    object
 71  2018     174 non-null    object
 72  2019     174 non-null    object
 73  2020     174 non-null    object
 74  2021     174 non-null    object
 75  2022     174 non-null    object
 76  2023     174 non-null    object
 77  2024     174 non-null    object
dtypes: object(78)
memory usage: 117.7+ KB

In [79]:
sipri_raw_tb5["Country"].unique()

array([nan, 'Africa', 'North Africa', 'Algeria', 'Libya', 'Morocco',
       'Tunisia', 'sub-Saharan Africa', 'Angola', 'Benin', 'Botswana',
       'Burkina Faso', 'Burundi', 'Cameroon', 'Cape Verde',
       'Central African Republic', 'Chad', 'Congo, DR', 'Congo, Republic',
       "Cote d'Ivoire", 'Djibouti', 'Equatorial Guinea', 'Eritrea',
       'Ethiopia', 'Gabon', 'Gambia, The', 'Ghana', 'Guinea',
       'Guinea-Bissau', 'Kenya', 'Lesotho', 'Liberia', 'Madagascar',
       'Malawi', 'Mali', 'Mauritania', 'Mauritius', 'Mozambique',
       'Namibia', 'Niger', 'Nigeria', 'Rwanda', 'Senegal', 'Seychelles',
       'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan', 'Sudan',
       'Eswatini', 'Tanzania', 'Togo', 'Uganda', 'Zambia', 'Zimbabwe',
       'Americas', 'Central America and the Caribbean', 'Belize',
       'Costa Rica', 'Cuba', 'Dominican Republic', 'El Salvador',
       'Guatemala', 'Haiti', 'Honduras', 'Jamaica', 'Mexico', 'Nicaragua',
       'Panama', 'Trinidad and Tobago', 'North America', 'Canada',
       'United States of America', 'South America', 'Argentina',
       'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Guyana',
       'Paraguay', 'Peru', 'Uruguay', 'Venezuela', 'Asia & Oceania',
       'Oceania', 'Australia', 'Fiji', 'New Zealand', 'Papua New Guinea',
       'South Asia', 'Afghanistan', 'Bangladesh', 'India', 'Nepal',
       'Pakistan', 'Sri Lanka', 'East Asia', 'China', 'Japan',
       'Korea, North', 'Korea, South', 'Mongolia', 'Taiwan',
       'South East Asia', 'Brunei', 'Cambodia', 'Indonesia', 'Laos',
       'Malaysia', 'Myanmar', 'Philippines', 'Singapore', 'Thailand',
       'Timor Leste', 'Viet Nam', 'Central Asia', 'Kazakhstan',
       'Kyrgyz Republic', 'Tajikistan', 'Turkmenistan', 'Uzbekistan',
       'Europe', 'Central Europe', 'Albania', 'Bosnia and Herzegovina',
       'Bulgaria', 'Croatia', 'Czechia', 'Czechoslovakia', 'Estonia',
       'German Democratic Republic', 'Hungary', 'Kosovo', 'Latvia',
       'Lithuania', 'North Macedonia', 'Montenegro', 'Poland', 'Romania',
       'Serbia', 'Slovakia', 'Slovenia', 'Yugoslavia', 'Eastern Europe',
       'Armenia', 'Azerbaijan', 'Belarus', 'Georgia', 'Moldova', 'Russia',
       'Ukraine', 'USSR', 'Western Europe', 'Austria', 'Belgium',
       'Cyprus', 'Denmark', 'Finland', 'France', 'Germany', 'Greece',
       'Iceland', 'Ireland', 'Italy', 'Luxembourg', 'Malta',
       'Netherlands', 'Norway', 'Portugal', 'Spain', 'Sweden',
       'Switzerland', 'United Kingdom', 'European Union', 'Middle East',
       'Bahrain', 'Egypt', 'Iran', 'Iraq', 'Israel', 'Jordan', 'Kuwait',
       'Lebanon', 'Oman', 'Qatar', 'Saudi Arabia', 'Syria', 'Türkiye',
       'United Arab Emirates', 'Yemen, North', 'Yemen'], dtype=object)

After a quick glance, we've identified a few cleaning tasks:
- Remove unwanted columns
- Pivot year columns
- Remove regions
- Filter data
- Define each data type for each column
- Rename country names (if needed)
- Rename column names


We need to perform these tasks for each table. Then, we need to
- [ ] Join the three tables
  
### Remove unwanted columns
Remove `Notes`.

In [80]:
columns_to_drop = sipri_raw_tb5.columns[1]
sipri_raw_tb5 = sipri_raw_tb5.drop(columns=columns_to_drop)

In [81]:
sipri_raw_tb5.head()

,Country,1949,1950,1951,1952,1953,1954,1955,1956,1957,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,North Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Algeria,...,...,...,...,...,...,...,...,...,...,10407.345244361462,10217.081699569308,10073.364021301344,9583.7242883703,10303.60057521065,9708.277440227255,9112.461105348943,9145.810174207281,18263.96796826213,21811.24255503127
4,Libya,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,1214.8645582452625,1573.6827773146888,...

### Pivot Year Columns

In [82]:
columns_to_pivot = sipri_raw_tb5.columns[1:]
sipri_raw_tb5 = sipri_raw_tb5.melt(
    id_vars="Country",
    value_vars=columns_to_pivot,
    var_name="year",
    value_name="military_expenditures_usd_2022")

In [83]:
sipri_raw_tb5

                    Country  year military_expenditures_usd_2022
0                       NaN  1949                            NaN
1                    Africa  1949                            NaN
2              North Africa  1949                            NaN
3                   Algeria  1949                            ...
4                     Libya  1949                            ...
...                     ...   ...                            ...
14663                 Syria  2024                            ...
14664               Türkiye  2024             24978.735534603824
14665  United Arab Emirates  2024                            ...
14666          Yemen, North  2024                            xxx
14667                 Yemen  2024                            ...

[14668 rows x 3 columns]

### Remove regions
We can perform this task by cleaning null values from our pivoted column.

In [84]:
sipri_raw_tb5 = sipri_raw_tb5.dropna(subset=["military_expenditures_usd_2022"])

In [85]:
sipri_raw_tb5

                    Country  year military_expenditures_usd_2022
3                   Algeria  1949                            ...
4                     Libya  1949                            ...
5                   Morocco  1949                            ...
6                   Tunisia  1949                            ...
8                    Angola  1949                            ...
...                     ...   ...                            ...
14663                 Syria  2024                            ...
14664               Türkiye  2024             24978.735534603824
14665  United Arab Emirates  2024                            ...
14666          Yemen, North  2024                            xxx
14667                 Yemen  2024                            ...

[13224 rows x 3 columns]

In [86]:
# Check for empty rows
sipri_raw_tb5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13224 entries, 3 to 14667
Data columns (total 3 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Country                         13224 non-null  object
 1   year                            13224 non-null  object
 2   military_expenditures_usd_2022  13224 non-null  object
dtypes: object(3)
memory usage: 413.2+ KB

### Define data types
We need to:
- Convert `year` to `int`.
- Convert `military_expenditures_usd_2022` to `float`.
  - First, convert missing values signed as `xxx` to `NaN`.

In [87]:
# Identify non-numeric values
non_numeric_rows = sipri_raw_tb5[pd.to_numeric(sipri_raw_tb5["military_expenditures_usd_2022"], errors="coerce").isna()]
non_numeric_rows

                    Country  year military_expenditures_usd_2022
3                   Algeria  1949                            ...
4                     Libya  1949                            ...
5                   Morocco  1949                            ...
6                   Tunisia  1949                            ...
8                    Angola  1949                            ...
...                     ...   ...                            ...
14661                 Qatar  2024                            ...
14663                 Syria  2024                            ...
14665  United Arab Emirates  2024                            ...
14666          Yemen, North  2024                            xxx
14667                 Yemen  2024                            ...

[4378 rows x 3 columns]

In [88]:
non_numeric_rows["military_expenditures_usd_2022"].unique()

array(['...', 'xxx'], dtype=object)

Ok! We've identified our null values. We need to replace them with NaN and convert the column to numeric.

In [89]:
# Replace non-numeric values with NaN
sipri_raw_tb5.loc[:,"military_expenditures_usd_2022"] = pd.to_numeric(
    sipri_raw_tb5["military_expenditures_usd_2022"], errors="coerce"
)

In [90]:
sipri_raw_tb5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13224 entries, 3 to 14667
Data columns (total 3 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Country                         13224 non-null  object
 1   year                            13224 non-null  object
 2   military_expenditures_usd_2022  8846 non-null   object
dtypes: object(3)
memory usage: 413.2+ KB

We can now remove NaN values.

In [91]:
sipri_raw_tb5 = sipri_raw_tb5.dropna(subset=["military_expenditures_usd_2022"])
sipri_raw_tb5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8846 entries, 58 to 14664
Data columns (total 3 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Country                         8846 non-null   object
 1   year                            8846 non-null   object
 2   military_expenditures_usd_2022  8846 non-null   object
dtypes: object(3)
memory usage: 276.4+ KB

Great! Let's move on. We now need to convert `year` to `int`.

In [92]:
sipri_raw_tb5 = sipri_raw_tb5.copy()
sipri_raw_tb5["year"] = sipri_raw_tb5["year"].astype(int)
sipri_raw_tb5["military_expenditures_usd_2022"] = sipri_raw_tb5["military_expenditures_usd_2022"].astype(float)

In [93]:
sipri_raw_tb5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8846 entries, 58 to 14664
Data columns (total 3 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Country                         8846 non-null   object
 1   year                            8846 non-null   int64
 2   military_expenditures_usd_2022  8846 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 276.4+ KB

### Filter data
We need to get:
- Data from 1990 onwards
- Limit our request to European countries only.

Let's start with the first task.

In [94]:
# Get years from 1990 to 2024
years = sipri_raw_tb5["year"].astype(int)
years = years[(years >= 1993) & (years <= 2024)]
years = years.unique()
years

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024])

In [95]:
# Filter the dataset using the `years` variable as filter
sipri_raw_tb5 = sipri_raw_tb5[sipri_raw_tb5["year"].isin(years)]
sipri_raw_tb5

            Country  year  military_expenditures_usd_2022
8495        Algeria  1993                     1276.911083
8497        Morocco  1993                     1251.786538
8498        Tunisia  1993                      276.167135
8500         Angola  1993                     1774.397877
8502       Botswana  1993                      185.671483
...             ...   ...                             ...
14658        Kuwait  2024                     7792.925566
14659       Lebanon  2024                      635.471572
14660          Oman  2024                     5988.296489
14662  Saudi Arabia  2024                    80330.666667
14664       Türkiye  2024                    24978.735535

[4904 rows x 3 columns]

In [96]:
sipri_raw_tb5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4904 entries, 8495 to 14664
Data columns (total 3 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Country                         4904 non-null   object
 1   year                            4904 non-null   int64
 2   military_expenditures_usd_2022  4904 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 153.2+ KB

Let's now get a list of countries and return only a list of European countries.

In [97]:
sipri_raw_tb5["Country"].sort_values().unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahrain',
       'Bangladesh', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Cape Verde', 'Central African Republic', 'Chad',
       'Chile', 'China', 'Colombia', 'Congo, DR', 'Congo, Republic',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus',
       'Czechia', 'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador',
       'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'European Union', 'Fiji', 'Finland',
       'France', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Korea, North', 'Korea, South',
       'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Laos', 'Latvia', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Malta', 'Mauritania',
       'Mauritius', 'Mexico', 'Moldova', 'Mongolia', 'Montenegro',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Slovakia', 'Slovenia', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Sweden', 'Switzerland', 'Syria',
       'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor Leste',
       'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkmenistan',
       'Türkiye', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States of America', 'Uruguay',
       'Uzbekistan', 'Venezuela', 'Viet Nam', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [98]:
# List European countries
european_countries = [
    "Albania", "Armenia", "Austria", "Azerbaijan", 
    "Belarus", "Belgium", "Bosnia and Herzegovina", "Bulgaria",
    "Croatia", "Cyprus", "Czechia", "Czechoslovakia", "Denmark",
    "Estonia", "Finland", "France", "Georgia",
    "Germany", "Greece", "Hungary", "Iceland", 
    "Ireland", "Italy", "Kosovo", "Latvia", "Lithuania",
    "Luxembourg", "Malta", "Moldova", "Montenegro",
    "Netherlands", "North Macedonia", "Norway", "Poland",
    "Portugal", "Romania", "Russia", "Serbia", 
    "Slovakia", "Slovenia", "Spain", "Sweden",
    "Switzerland", "Türkiye", "USSR", "Ukraine",
    "United Kingdom", "Yugoslavia"
]

sipri_raw_tb5 = sipri_raw_tb5[sipri_raw_tb5["Country"].isin(european_countries)]
sipri_raw_tb5

              Country  year  military_expenditures_usd_2022
8617          Albania  1993                       39.289843
8619         Bulgaria  1993                      282.674243
8620          Croatia  1993                      577.978269
8621          Czechia  1993                      815.585467
8623          Estonia  1993                       13.146560
...               ...   ...                             ...
14646           Spain  2024                    24615.397929
14647          Sweden  2024                    12040.289403
14648     Switzerland  2024                     6722.303544
14649  United Kingdom  2024                    81763.173070
14664         Türkiye  2024                    24978.735535

[1394 rows x 3 columns]

In [99]:
sipri_raw_tb5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1394 entries, 8617 to 14664
Data columns (total 3 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Country                         1394 non-null   object
 1   year                            1394 non-null   int64
 2   military_expenditures_usd_2022  1394 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 43.6+ KB

Great! Now, our values are written in millions but not literally - we need to multiply each row value by `1_000_000`

In [100]:
sipri_raw_tb5["military_expenditures_usd_2022"] = sipri_raw_tb5["military_expenditures_usd_2022"] * 1_000_000
sipri_raw_tb5

C:\Users\felip\AppData\Local\Temp\ipykernel_14228\2468274360.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sipri_raw_tb5["military_expenditures_usd_2022"] = sipri_raw_tb5["military_expenditures_usd_2022"] * 1_000_000

              Country  year  military_expenditures_usd_2022
8617          Albania  1993                    3.928984e+07
8619         Bulgaria  1993                    2.826742e+08
8620          Croatia  1993                    5.779783e+08
8621          Czechia  1993                    8.155855e+08
8623          Estonia  1993                    1.314656e+07
...               ...   ...                             ...
14646           Spain  2024                    2.461540e+10
14647          Sweden  2024                    1.204029e+10
14648     Switzerland  2024                    6.722304e+09
14649  United Kingdom  2024                    8.176317e+10
14664         Türkiye  2024                    2.497874e+10

[1394 rows x 3 columns]

Awesome! Now, we just need to rename our `Country` column to `country`.

In [101]:
sipri_raw_tb5 = sipri_raw_tb5.rename(columns={
    "Country": "country"
})

In [102]:
sipri_raw_tb5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1394 entries, 8617 to 14664
Data columns (total 3 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country                         1394 non-null   object
 1   year                            1394 non-null   int64
 2   military_expenditures_usd_2022  1394 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 43.6+ KB

In [103]:
sipri_raw_tb5.describe()

              year  military_expenditures_usd_2022
count  1394.000000                    1.394000e+03
mean   2008.855811                    7.682566e+09
std       9.145785                    1.559756e+10
min    1993.000000                    0.000000e+00
25%    2001.000000                    2.960055e+08
50%    2009.000000                    1.446634e+09
75%    2017.000000                    5.524561e+09
max    2024.000000                    1.489673e+11

Awesome! Our table is ready. We need to perform these same tasks on tables #6 and #7. It would be the right time to create a few functions to automate this process.

In [104]:
def transform_data(raw_data, table_number, column_name, start_year, end_year, countries_list, renamed_column) -> pd.DataFrame:
    """
    Reads the `.csv` file and performs a series of transformations.
    """
    # Initialize header_row
    header_row = None

    # Debug: Print the table being processed
    print(f"Processing table {table_number}...")

    # Dynamically find the header row
    with open(f"{raw_data}sipri_data_raw_tb_{table_number}.csv", "r") as file:
        for i, line in enumerate(file):
            if "Country" in line:
                header_row = i  # Define header if `Country` is a value
                break

    # Debug: Print the header_row value
    print(f"Header row for table {table_number}: {header_row}")

    # Raise an error if header_row is not found
    if header_row is None:
        raise ValueError(f"'Country' header not found in table {table_number}")

    # Read the file
    df = pd.read_csv(f"{raw_data}sipri_data_raw_tb_{table_number}.csv", skiprows=header_row, header=0)

    print(f"\nFirst 3 rows: \n{df.head(3)}")
    
    # Dynamically identify columns to drop
    # Keep "Country" and all columns starting with a year
    columns_to_keep = ["Country"] + [col for col in df.columns if col.strip().isdigit()]
    df = df[columns_to_keep]
    
    # Pivot year columns
    columns_to_pivot = df.columns[1:]
    df = df.melt(
        id_vars="Country",
        value_vars=columns_to_pivot,
        var_name="year",
        value_name=column_name
    )

    # Remove regions
    df = df.dropna(subset=[column_name])

    # Replace non-numeric values with NaN
    df.loc[:, column_name] = pd.to_numeric(df[column_name], errors="coerce")

    # Convert data types to numeric
    df["year"] = df["year"].astype(int)
    df[column_name] = df[column_name].astype(float)

    # Filter the dataset by years
    df = df[(df["year"] >= start_year) & (df["year"] <= end_year)]

    # Filter by European countries
    df = df[df["Country"].isin(countries_list)]

    # If table is 5 or 6, multiply column value by 1,000,000
    if table_number in [4, 5]:
        df[column_name] *= 1_000_000

    # Rename `Country` column
    df = df.rename(columns={
    "Country": renamed_column
})

    print(f"Table {table_number} output: \n{df.head()}")
    return df

In [105]:
# Define the parameters for each table
tables = [
    {"table_number" : 4, "column_name": "military_expenditures_usd_2022"},
    {"table_number" : 5, "column_name": "military_expenditures_current_usd"},
    {"table_number" : 6, "column_name": "share_GDP"},
    {"table_number" : 8, "column_name": "share_govt"},
]

start_year = 1993
end_year = 2024

countries_list = [
    "Albania", "Armenia", "Austria", "Azerbaijan", 
    "Belarus", "Belgium", "Bosnia and Herzegovina", "Bulgaria",
    "Croatia", "Czechia", "Czechoslovakia", "Denmark",
    "Estonia", "Finland", "France", "Georgia",
    "Germany", "Greece", "Hungary", "Iceland", 
    "Ireland", "Italy", "Kosovo", "Latvia", "Lithuania",
    "Luxembourg", "Malta", "Moldova", "Montenegro",
    "Netherlands", "North Macedonia", "Norway", "Poland",
    "Portugal", "Romania", "Russia", "Serbia", 
    "Slovakia", "Slovenia", "Spain", "Sweden",
    "Switzerland", "Türkiye", "USSR", "Ukraine",
    "United Kingdom", "Yugoslavia"
]

renamed_column = "country"

In [106]:
# Store the resulting DataFrames in variables
sipri_tb4, sipri_tb5, sipri_tb6, sipri_tb8 = [
    transform_data(
        raw_data=raw_data,
        table_number=table["table_number"],
        column_name=table["column_name"],
        start_year=start_year,
        end_year=end_year,
        countries_list=countries_list,
        renamed_column=renamed_column
    )
for table in tables]

Processing table 4...
Header row for table 4: 5

First 3 rows:
        Country  Unnamed: 1 Notes 1949 1950 1951 1952 1953 1954 1955  ...  \
0           NaN         NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...
1        Africa         NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...
2  North Africa         NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...

  2015 2016 2017 2018 2019 2020 2021 2022 2023 2024
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[3 rows x 79 columns]
Table 4 output:
                     country  year  military_expenditures_usd_2022
8617                 Albania  1993                    1.772197e+08
8618  Bosnia and Herzegovina  1993                             NaN
8619                Bulgaria  1993                    1.275756e+09
8620                 Croatia  1993                    2.893439e+09
8621                 Czechia  1993                    3.642702e+09
Processing table 5...
Header row for table 5: 5

First 3 rows:
        Country Notes 1949 1950 1951 1952 1953 1954 1955 1956  ... 2015 2016  \
0           NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
1        Africa   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
2  North Africa   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN

  2017 2018 2019 2020 2021 2022 2023 2024
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[3 rows x 78 columns]
Table 5 output:
                     country  year  military_expenditures_current_usd
8617                 Albania  1993                       3.928984e+07
8618  Bosnia and Herzegovina  1993                                NaN
8619                Bulgaria  1993                       2.826742e+08
8620                 Croatia  1993                       5.779783e+08
8621                 Czechia  1993                       8.155855e+08
Processing table 6...
Header row for table 6: 5

First 3 rows:
        Country Notes 1949 1950 1951 1952 1953 1954 1955 1956  ... 2015 2016  \
0           NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
1        Africa   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
2  North Africa   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN

  2017 2018 2019 2020 2021 2022 2023 2024
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[3 rows x 78 columns]
Table 6 output:
                     country  year  share_GDP
8617                 Albania  1993   0.031995
8618  Bosnia and Herzegovina  1993        NaN
8619                Bulgaria  1993   0.026093
8620                 Croatia  1993   0.107268
8621                 Czechia  1993   0.023304
Processing table 8...
Header row for table 8: 7

First 3 rows:
        Country Notes  Reporting year 1988 1989 1990 1991 1992 1993 1994  ...  \
0           NaN   NaN             NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...
1        Africa   NaN             NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...
2  North Africa   NaN             NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...

  2015 2016 2017 2018 2019 2020 2021 2022 2023 2024
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[3 rows x 40 columns]
Table 8 output:
                     country  year  share_govt
1090                 Albania  1993         NaN
1091  Bosnia and Herzegovina  1993         NaN
1092                Bulgaria  1993         NaN
1093                 Croatia  1993    0.250241
1094                 Czechia  1993         NaN

Ok! Let's move on to the next part.

## Merge all tables
We will now merge all the tables and get the following structure:
| country    | year | military_expenditures_usd_2022  | military_expenditures_current_usd | share_GDP | share_govt | 
| -------- | ------- | ------- | ------- | ------- | ------- |

In [107]:
sipri_joined_table = sipri_tb4.merge(sipri_tb5, on=["country", "year"],how="outer") \
                              .merge(sipri_tb6, on=["country", "year"], how="outer") \
                              .merge(sipri_tb8, on=["country", "year"], how="outer") 

sipri_joined_table.head()

,country,year,military_expenditures_usd_2022,military_expenditures_current_usd,share_GDP,share_govt
0,Albania,1993,1.772197e+08,3.928984e+07,0.031995,NaN
1,Albania,1994,1.694002e+08,4.964950e+07,0.025478,NaN
2,Albania,1995,1.578554e+08,5.090752e+07,0.020536,NaN
3,Albania,1996,1.417564e+08,4.571336e+07,0.013790,NaN
4,Albania,1997,9.897513e+07,2.982549e+07,0.012831,0.044247

In [108]:
# Sample data from a single country.
sipri_joined_table[sipri_joined_table["country"]=="France"]

,country,year,military_expenditures_usd_2022,military_expenditures_current_usd,share_GDP,share_govt
448,France,1993,5.388573e+10,3.577527e+10,0.027217,0.048140
449,France,1994,5.416296e+10,3.728861e+10,0.026907,0.048148
450,France,1995,5.148169e+10,4.012402e+10,0.025154,0.044881
451,France,1996,5.025712e+10,3.897773e+10,0.024377,0.043518
452,France,1997,5.043869e+10,3.469790e+10,0.023940,0.043084
453,France,1998,4.909804e+10,3.363356e+10,0.022468,0.041625
454,France,1999,4.951106e+10,3.267271e+10,0.021982,0.040966
455,France,2000,4.895103e+10,2.840314e+10,0.020922,0.039759
456,France,2001,4.880012e+10,2.795157e+10,0.020415,0.038649
457,France,2002,4.980277e+10,3.057840e+10,0.020586,0.038175
458,France,2003,5.130506e+10,3.856912e+10,0.021065,0.038750
459,France,2004,5.270575e+10,4.452458e+10,0.021142,0.039151
460,France,2005,5.162542e+10,4.444205e+10,0.020281,0.037378
461,France,2006,5.186329e+10,4.579215e+10,0.019774,0.036790
462,France,2007,5.184375e+10,5.068447e+10,0.019110,0.035632
463,France,2008,5.146698e+10,5.536597e+10,0.018993,0.034991
464,France,2009,5.527483e+10,5.644146e+10,0.020988,0.036189
465,France,2010,5.265459e+10,5.204406e+10,0.019686,0.034108
466,France,2011,5.108874e+10,5.412087e+10,0.018879,0.033117
467,France,2012,5.030397e+10,5.021651e+10,0.018715,0.032330
468,France,2013,4.997805e+10,5.200146e+10,0.018471,0.031526
469,France,2014,5.084782e+10,5.313475e+10,0.018595,0.031846
470,France,2015,5.223883e+10,4.564747e+10,0.018697,0.032463
471,France,2016,5.235438e+10,4.570338e+10,0.018517,0.032272
472,France,2017,5.322632e+10,4.762808e+10,0.018523,0.032122
473,France,2018,5.352960e+10,5.132136e+10,0.018460,0.032749
474,France,2019,5.487277e+10,5.045455e+10,0.018529,0.033479
475,France,2020,5.679626e+10,5.342300e+10,0.020217,0.032768
476,France,2021,5.921448e+10,5.873463e+10,0.019802,0.033302
477,France,2022,5.890431e+10,5.467744e+10,0.019577,0.033524
478,France,2023,5.949196e+10,5.949196e+10,0.019510,0.034234
479,France,2024,6.313497e+10,6.467502e+10,0.020526,0.035862

Awesome! We can now export our `SIPRI` dataset to the `transformed` folder.

In [109]:
# Export output to transformed
sipri_joined_table.to_csv(f"{transformed_data}sipri_dataset.csv", index=False)

# Data transformation | Coordinates for City Capitals
Our goals here are:
- Import the raw data.
- Check its structure.
- Select targeted countries (European).
- Rename variables and values.
  - Make sure that names of countries matches those from SIPRI dataset.
- Create columns
  - Distance, in km and miles, from the city capital to Moscow.
## Import data

In [110]:
city_coords = pd.read_csv(f"{raw_data}city_capitals_coords.csv")

In [111]:
city_coords

,Country,Capital City,Latitude,Longitude,Population,Capital Type
0,Afghanistan,Kabul,34.5289,69.1725,4011770,Capital
1,Albania,Tiranë (Tirana),41.3275,19.8189,475577,Capital
2,Algeria,El Djazaïr (Algiers),36.7525,3.0420,2693542,Capital
3,American Samoa,Pago Pago,-14.2781,-170.7025,48526,Capital
4,Andorra,Andorra la Vella,42.5078,1.5211,22614,Capital
...,...,...,...,...,...,...
229,Wallis and Futuna Islands,Matu-Utu,-13.2816,-176.1745,1025,Capital
230,Western Sahara,El Aaiún,27.1532,-13.2014,232388,Capital
231,Yemen,Sana'a',15.3531,44.2078,2779317,Capital
232,Zambia,Lusaka,-15.4134,28.2771,2523844,Capital
233,Zimbabwe,Harare,-17.8294,31.0539,1515016,Capital

## Check the table structure

In [112]:
city_coords.shape

(234, 6)

In [113]:
city_coords.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       234 non-null    object
 1   Capital City  234 non-null    object
 2   Latitude      234 non-null    float64
 3   Longitude     234 non-null    float64
 4   Population    234 non-null    int64
 5   Capital Type  234 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 11.1+ KB

There is not much to do here. Our table seems to be in good shape. We can focus on:
- Selecting our countries
- Removing unnecessary columns

## Select countries, remove columns

In [114]:
city_coords["Country"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Anguilla', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'British Virgin Islands',
       'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Caribbean Netherlands', 'Cayman Islands',
       'Central African Republic', 'Chad', 'Channel Islands', 'Chile',
       'China', 'China, Hong Kong SAR', 'China, Macao SAR',
       'China, Taiwan Province of China', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', "Côte d'Ivoire", 'Croatia', 'Cuba',
       'Curaçao', 'Cyprus', 'Czechia', "Dem. People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Ethiopia', 'Faeroe Islands', 'Falkland Islands (Malvinas)',
       'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar',
       'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Holy See', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Isle of Man',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius',
       'Mayotte', 'Mexico', 'Micronesia (Fed. States of)', 'Monaco',
       'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
       'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'Niue', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan',
       'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Republic of Korea', 'Republic of Moldova', 'Réunion', 'Romania',
       'Russian Federation', 'Rwanda', 'Saint Helena',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'State of Palestine', 'Sudan', 'Suriname',
       'Swaziland', 'Sweden', 'Switzerland', 'Syrian Arab Republic',
       'Tajikistan', 'TFYR Macedonia', 'Thailand', 'Timor-Leste', 'Togo',
       'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda',
       'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United Republic of Tanzania', 'United States of America',
       'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam',
       'Wallis and Futuna Islands', 'Western Sahara', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [115]:
city_coords_countries_list = [
    "Albania", "Armenia", "Austria", "Azerbaijan", 
    "Belarus", "Belgium", "Bosnia and Herzegovina", "Bulgaria",
    "Croatia", "Czechia", "Cyprus", "Denmark",
    "Estonia", "Finland", "France", "Georgia",
    "Germany", "Greece", "Hungary", "Iceland", 
    "Ireland", "Italy", "Kosovo", "Latvia", "Lithuania",
    "Luxembourg", "Malta", "Republic of Moldova", "Montenegro",
    "Netherlands", "North Macedonia", "Norway", "Poland",
    "Portugal", "Romania", "Russian Federation", "Serbia", 
    "Slovakia", "Slovenia", "Spain", "Sweden", "TFYR Macedonia",
    "Switzerland", "Turkey", "Ukraine",
    "United Kingdom", "Yugoslavia"
]

In [116]:
# Select countries using list
city_coords = city_coords[city_coords["Country"].isin(city_coords_countries_list)].reset_index(drop=True)

In [117]:
city_coords

,Country,Capital City,Latitude,Longitude,Population,Capital Type
0,Albania,Tiranë (Tirana),41.3275,19.8189,475577,Capital
1,Armenia,Yerevan,40.1820,44.5146,1080324,Capital
2,Austria,Wien (Vienna),48.2064,16.3707,1900547,Capital
3,Azerbaijan,Baku,40.3777,49.8920,2285729,Capital
4,Belarus,Minsk,53.9000,27.5667,2004672,Capital
5,Belgium,Bruxelles-Brussel,50.8467,4.3499,2049510,Capital
6,Bosnia and Herzegovina,Sarajevo,43.8486,18.3564,342577,Capital
7,Bulgaria,Sofia,42.6975,23.3242,1272418,Capital
8,Croatia,Zagreb,45.8144,15.9780,685587,Capital
9,Cyprus,Lefkosia (Nicosia),35.1595,33.3669,269469,Capital
10,Czechia,Praha (Prague),50.0880,14.4208,1291552,Capital
11,Denmark,København (Copenhagen),55.6759,12.5655,1320826,Capital
12,Estonia,Tallinn,59.4370,24.7535,437027,Capital
13,Finland,Helsinki,60.1692,24.9402,1279096,Capital
14,France,Paris,48.8534,2.3488,10900952,Capital
15,Georgia,Tbilisi,41.6941,44.8337,1077333,Capital
16,Germany,Berlin,52.5244,13.4105,3552123,Capital
17,Greece,Athínai (Athens),37.9534,23.7490,3155600,Capital
18,Hungary,Budapest,47.4980,19.0399,1759497,Capital
19,Iceland,Reykjavík,64.1355,-21.8954,216364,Capital
20,Ireland,Dublin,53.3331,-6.2489,1201426,Capital
21,Italy,Roma (Rome),41.8947,12.4811,4209710,Capital
22,Latvia,Riga,56.9460,24.1059,637089,Capital
23,Lithuania,Vilnius,54.6892,25.2798,536055,Capital
24,Luxembourg,Luxembourg,49.6117,6.1300,119752,Capital
25,Malta,Valletta,35.8997,14.5147,212768,Capital
26,Montenegro,Podgorica,42.4411,19.2636,177177,Capital
27,Netherlands,Amsterdam,52.3740,4.8897,1131690,Capital
28,Norway,Oslo,59.9127,10.7461,1012225,Capital
29,Poland,Warszawa (Warsaw),52.2298,21.0118,1767798,Capital
30,Portugal,Lisboa (Lisbon),38.7169,-9.1399,2927316,Capital
31,Republic of Moldova,Chişinău,47.0056,28.8575,509707,Capital
32,Romania,Bucuresti (Bucharest),44.4328,26.1043,1821380,Capital
33,Russian Federation,Moskva (Moscow),55.7550,37.6218,12409738,Capital
34,Serbia,Beograd (Belgrade),44.8176,20.4633,1389351,Capital
35,Slovakia,Bratislava,48.1482,17.1067,429920,Capital
36,Slovenia,Ljubljana,46.0511,14.5051,286491,Capital
37,Spain,Madrid,40.4165,-3.7026,6497124,Capital
38,Sweden,Stockholm,59.3326,18.0649,1582968,Capital
39,Switzerland,Bern,46.9481,7.4474,422153,Capital
40,TFYR Macedonia,Skopje,42.0000,21.4333,584208,Capital
41,Turkey,Ankara,39.9199,32.8543,4919074,Capital
42,Ukraine,Kyiv (Kiev),50.4454,30.5186,2956706,Capital
43,United Kingdom,London,51.5085,-0.1257,9046485,Capital

In [118]:
city_coords

,Country,Capital City,Latitude,Longitude,Population,Capital Type
0,Albania,Tiranë (Tirana),41.3275,19.8189,475577,Capital
1,Armenia,Yerevan,40.1820,44.5146,1080324,Capital
2,Austria,Wien (Vienna),48.2064,16.3707,1900547,Capital
3,Azerbaijan,Baku,40.3777,49.8920,2285729,Capital
4,Belarus,Minsk,53.9000,27.5667,2004672,Capital
5,Belgium,Bruxelles-Brussel,50.8467,4.3499,2049510,Capital
6,Bosnia and Herzegovina,Sarajevo,43.8486,18.3564,342577,Capital
7,Bulgaria,Sofia,42.6975,23.3242,1272418,Capital
8,Croatia,Zagreb,45.8144,15.9780,685587,Capital
9,Cyprus,Lefkosia (Nicosia),35.1595,33.3669,269469,Capital
10,Czechia,Praha (Prague),50.0880,14.4208,1291552,Capital
11,Denmark,København (Copenhagen),55.6759,12.5655,1320826,Capital
12,Estonia,Tallinn,59.4370,24.7535,437027,Capital
13,Finland,Helsinki,60.1692,24.9402,1279096,Capital
14,France,Paris,48.8534,2.3488,10900952,Capital
15,Georgia,Tbilisi,41.6941,44.8337,1077333,Capital
16,Germany,Berlin,52.5244,13.4105,3552123,Capital
17,Greece,Athínai (Athens),37.9534,23.7490,3155600,Capital
18,Hungary,Budapest,47.4980,19.0399,1759497,Capital
19,Iceland,Reykjavík,64.1355,-21.8954,216364,Capital
20,Ireland,Dublin,53.3331,-6.2489,1201426,Capital
21,Italy,Roma (Rome),41.8947,12.4811,4209710,Capital
22,Latvia,Riga,56.9460,24.1059,637089,Capital
23,Lithuania,Vilnius,54.6892,25.2798,536055,Capital
24,Luxembourg,Luxembourg,49.6117,6.1300,119752,Capital
25,Malta,Valletta,35.8997,14.5147,212768,Capital
26,Montenegro,Podgorica,42.4411,19.2636,177177,Capital
27,Netherlands,Amsterdam,52.3740,4.8897,1131690,Capital
28,Norway,Oslo,59.9127,10.7461,1012225,Capital
29,Poland,Warszawa (Warsaw),52.2298,21.0118,1767798,Capital
30,Portugal,Lisboa (Lisbon),38.7169,-9.1399,2927316,Capital
31,Republic of Moldova,Chişinău,47.0056,28.8575,509707,Capital
32,Romania,Bucuresti (Bucharest),44.4328,26.1043,1821380,Capital
33,Russian Federation,Moskva (Moscow),55.7550,37.6218,12409738,Capital
34,Serbia,Beograd (Belgrade),44.8176,20.4633,1389351,Capital
35,Slovakia,Bratislava,48.1482,17.1067,429920,Capital
36,Slovenia,Ljubljana,46.0511,14.5051,286491,Capital
37,Spain,Madrid,40.4165,-3.7026,6497124,Capital
38,Sweden,Stockholm,59.3326,18.0649,1582968,Capital
39,Switzerland,Bern,46.9481,7.4474,422153,Capital
40,TFYR Macedonia,Skopje,42.0000,21.4333,584208,Capital
41,Turkey,Ankara,39.9199,32.8543,4919074,Capital
42,Ukraine,Kyiv (Kiev),50.4454,30.5186,2956706,Capital
43,United Kingdom,London,51.5085,-0.1257,9046485,Capital

In [119]:
# Remove columns
city_coords = city_coords.iloc[:, :-2]

In [120]:
city_coords

                   Country            Capital City  Latitude  Longitude
0                  Albania         Tiranë (Tirana)   41.3275    19.8189
1                  Armenia                 Yerevan   40.1820    44.5146
2                  Austria           Wien (Vienna)   48.2064    16.3707
3               Azerbaijan                    Baku   40.3777    49.8920
4                  Belarus                   Minsk   53.9000    27.5667
5                  Belgium       Bruxelles-Brussel   50.8467     4.3499
6   Bosnia and Herzegovina                Sarajevo   43.8486    18.3564
7                 Bulgaria                   Sofia   42.6975    23.3242
8                  Croatia                  Zagreb   45.8144    15.9780
9                   Cyprus      Lefkosia (Nicosia)   35.1595    33.3669
10                 Czechia          Praha (Prague)   50.0880    14.4208
11                 Denmark  København (Copenhagen)   55.6759    12.5655
12                 Estonia                 Tallinn   59.4370    24.7535
13                 Finland                Helsinki   60.1692    24.9402
14                  France                   Paris   48.8534     2.3488
15                 Georgia                 Tbilisi   41.6941    44.8337
16                 Germany                  Berlin   52.5244    13.4105
17                  Greece        Athínai (Athens)   37.9534    23.7490
18                 Hungary                Budapest   47.4980    19.0399
19                 Iceland               Reykjavík   64.1355   -21.8954
20                 Ireland                  Dublin   53.3331    -6.2489
21                   Italy             Roma (Rome)   41.8947    12.4811
22                  Latvia                    Riga   56.9460    24.1059
23               Lithuania                 Vilnius   54.6892    25.2798
24              Luxembourg              Luxembourg   49.6117     6.1300
25                   Malta                Valletta   35.8997    14.5147
26              Montenegro               Podgorica   42.4411    19.2636
27             Netherlands               Amsterdam   52.3740     4.8897
28                  Norway                    Oslo   59.9127    10.7461
29                  Poland       Warszawa (Warsaw)   52.2298    21.0118
30                Portugal         Lisboa (Lisbon)   38.7169    -9.1399
31     Republic of Moldova                Chişinău   47.0056    28.8575
32                 Romania   Bucuresti (Bucharest)   44.4328    26.1043
33      Russian Federation         Moskva (Moscow)   55.7550    37.6218
34                  Serbia      Beograd (Belgrade)   44.8176    20.4633
35                Slovakia              Bratislava   48.1482    17.1067
36                Slovenia               Ljubljana   46.0511    14.5051
37                   Spain                  Madrid   40.4165    -3.7026
38                  Sweden               Stockholm   59.3326    18.0649
39             Switzerland                    Bern   46.9481     7.4474
40          TFYR Macedonia                  Skopje   42.0000    21.4333
41                  Turkey                  Ankara   39.9199    32.8543
42                 Ukraine             Kyiv (Kiev)   50.4454    30.5186
43          United Kingdom                  London   51.5085    -0.1257

## Rename variables and values
Next, we need to:
- Rename country names (when necessary)
- Rename capital names (make them shorter)
- Rename column names

### Rename country names

In [121]:
sipri_joined_table["country"].unique()

array(['Albania', 'Armenia', 'Austria', 'Azerbaijan', 'Belarus',
       'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia',
       'Czechia', 'Czechoslovakia', 'Denmark', 'Estonia', 'Finland',
       'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland',
       'Ireland', 'Italy', 'Kosovo', 'Latvia', 'Lithuania', 'Luxembourg',
       'Malta', 'Moldova', 'Montenegro', 'Netherlands', 'North Macedonia',
       'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'Serbia',
       'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland',
       'Türkiye', 'USSR', 'Ukraine', 'United Kingdom', 'Yugoslavia'],
      dtype=object)

In [122]:
city_coords["Country"].unique()

array(['Albania', 'Armenia', 'Austria', 'Azerbaijan', 'Belarus',
       'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia',
       'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France',
       'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland',
       'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta',
       'Montenegro', 'Netherlands', 'Norway', 'Poland', 'Portugal',
       'Republic of Moldova', 'Romania', 'Russian Federation', 'Serbia',
       'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland',
       'TFYR Macedonia', 'Turkey', 'Ukraine', 'United Kingdom'],
      dtype=object)

In [123]:
city_coords = city_coords.replace(
    {"Country": {
        "Republic of Moldova": "Moldova",
        "Russian Federation": "Russia",
        "Turkey": "Türkiye",
        "TFYR Macedonia": "North Macedonia",
    }}
)

In [124]:
city_coords

                   Country            Capital City  Latitude  Longitude
0                  Albania         Tiranë (Tirana)   41.3275    19.8189
1                  Armenia                 Yerevan   40.1820    44.5146
2                  Austria           Wien (Vienna)   48.2064    16.3707
3               Azerbaijan                    Baku   40.3777    49.8920
4                  Belarus                   Minsk   53.9000    27.5667
5                  Belgium       Bruxelles-Brussel   50.8467     4.3499
6   Bosnia and Herzegovina                Sarajevo   43.8486    18.3564
7                 Bulgaria                   Sofia   42.6975    23.3242
8                  Croatia                  Zagreb   45.8144    15.9780
9                   Cyprus      Lefkosia (Nicosia)   35.1595    33.3669
10                 Czechia          Praha (Prague)   50.0880    14.4208
11                 Denmark  København (Copenhagen)   55.6759    12.5655
12                 Estonia                 Tallinn   59.4370    24.7535
13                 Finland                Helsinki   60.1692    24.9402
14                  France                   Paris   48.8534     2.3488
15                 Georgia                 Tbilisi   41.6941    44.8337
16                 Germany                  Berlin   52.5244    13.4105
17                  Greece        Athínai (Athens)   37.9534    23.7490
18                 Hungary                Budapest   47.4980    19.0399
19                 Iceland               Reykjavík   64.1355   -21.8954
20                 Ireland                  Dublin   53.3331    -6.2489
21                   Italy             Roma (Rome)   41.8947    12.4811
22                  Latvia                    Riga   56.9460    24.1059
23               Lithuania                 Vilnius   54.6892    25.2798
24              Luxembourg              Luxembourg   49.6117     6.1300
25                   Malta                Valletta   35.8997    14.5147
26              Montenegro               Podgorica   42.4411    19.2636
27             Netherlands               Amsterdam   52.3740     4.8897
28                  Norway                    Oslo   59.9127    10.7461
29                  Poland       Warszawa (Warsaw)   52.2298    21.0118
30                Portugal         Lisboa (Lisbon)   38.7169    -9.1399
31                 Moldova                Chişinău   47.0056    28.8575
32                 Romania   Bucuresti (Bucharest)   44.4328    26.1043
33                  Russia         Moskva (Moscow)   55.7550    37.6218
34                  Serbia      Beograd (Belgrade)   44.8176    20.4633
35                Slovakia              Bratislava   48.1482    17.1067
36                Slovenia               Ljubljana   46.0511    14.5051
37                   Spain                  Madrid   40.4165    -3.7026
38                  Sweden               Stockholm   59.3326    18.0649
39             Switzerland                    Bern   46.9481     7.4474
40         North Macedonia                  Skopje   42.0000    21.4333
41                 Türkiye                  Ankara   39.9199    32.8543
42                 Ukraine             Kyiv (Kiev)   50.4454    30.5186
43          United Kingdom                  London   51.5085    -0.1257

### Format city names
Next, we keep only the values in English when possible.

In [125]:
city_coords["Capital City"] = city_coords["Capital City"].apply(
    lambda x: x[x.find("(") + 1:x.find(")")] if "(" in x and ")" in x else x
)

In [126]:
city_coords

                   Country       Capital City  Latitude  Longitude
0                  Albania             Tirana   41.3275    19.8189
1                  Armenia            Yerevan   40.1820    44.5146
2                  Austria             Vienna   48.2064    16.3707
3               Azerbaijan               Baku   40.3777    49.8920
4                  Belarus              Minsk   53.9000    27.5667
5                  Belgium  Bruxelles-Brussel   50.8467     4.3499
6   Bosnia and Herzegovina           Sarajevo   43.8486    18.3564
7                 Bulgaria              Sofia   42.6975    23.3242
8                  Croatia             Zagreb   45.8144    15.9780
9                   Cyprus            Nicosia   35.1595    33.3669
10                 Czechia             Prague   50.0880    14.4208
11                 Denmark         Copenhagen   55.6759    12.5655
12                 Estonia            Tallinn   59.4370    24.7535
13                 Finland           Helsinki   60.1692    24.9402
14                  France              Paris   48.8534     2.3488
15                 Georgia            Tbilisi   41.6941    44.8337
16                 Germany             Berlin   52.5244    13.4105
17                  Greece             Athens   37.9534    23.7490
18                 Hungary           Budapest   47.4980    19.0399
19                 Iceland          Reykjavík   64.1355   -21.8954
20                 Ireland             Dublin   53.3331    -6.2489
21                   Italy               Rome   41.8947    12.4811
22                  Latvia               Riga   56.9460    24.1059
23               Lithuania            Vilnius   54.6892    25.2798
24              Luxembourg         Luxembourg   49.6117     6.1300
25                   Malta           Valletta   35.8997    14.5147
26              Montenegro          Podgorica   42.4411    19.2636
27             Netherlands          Amsterdam   52.3740     4.8897
28                  Norway               Oslo   59.9127    10.7461
29                  Poland             Warsaw   52.2298    21.0118
30                Portugal             Lisbon   38.7169    -9.1399
31                 Moldova           Chişinău   47.0056    28.8575
32                 Romania          Bucharest   44.4328    26.1043
33                  Russia             Moscow   55.7550    37.6218
34                  Serbia           Belgrade   44.8176    20.4633
35                Slovakia         Bratislava   48.1482    17.1067
36                Slovenia          Ljubljana   46.0511    14.5051
37                   Spain             Madrid   40.4165    -3.7026
38                  Sweden          Stockholm   59.3326    18.0649
39             Switzerland               Bern   46.9481     7.4474
40         North Macedonia             Skopje   42.0000    21.4333
41                 Türkiye             Ankara   39.9199    32.8543
42                 Ukraine               Kiev   50.4454    30.5186
43          United Kingdom             London   51.5085    -0.1257

### Rename columns

In [127]:
city_coords.rename(columns={
    "Country": "country",
    "Capital City": "capital_city",
    "Latitude": "latitude",
    "Longitude": "longitude"
}, inplace=True)

In [128]:
city_coords

                   country       capital_city  latitude  longitude
0                  Albania             Tirana   41.3275    19.8189
1                  Armenia            Yerevan   40.1820    44.5146
2                  Austria             Vienna   48.2064    16.3707
3               Azerbaijan               Baku   40.3777    49.8920
4                  Belarus              Minsk   53.9000    27.5667
5                  Belgium  Bruxelles-Brussel   50.8467     4.3499
6   Bosnia and Herzegovina           Sarajevo   43.8486    18.3564
7                 Bulgaria              Sofia   42.6975    23.3242
8                  Croatia             Zagreb   45.8144    15.9780
9                   Cyprus            Nicosia   35.1595    33.3669
10                 Czechia             Prague   50.0880    14.4208
11                 Denmark         Copenhagen   55.6759    12.5655
12                 Estonia            Tallinn   59.4370    24.7535
13                 Finland           Helsinki   60.1692    24.9402
14                  France              Paris   48.8534     2.3488
15                 Georgia            Tbilisi   41.6941    44.8337
16                 Germany             Berlin   52.5244    13.4105
17                  Greece             Athens   37.9534    23.7490
18                 Hungary           Budapest   47.4980    19.0399
19                 Iceland          Reykjavík   64.1355   -21.8954
20                 Ireland             Dublin   53.3331    -6.2489
21                   Italy               Rome   41.8947    12.4811
22                  Latvia               Riga   56.9460    24.1059
23               Lithuania            Vilnius   54.6892    25.2798
24              Luxembourg         Luxembourg   49.6117     6.1300
25                   Malta           Valletta   35.8997    14.5147
26              Montenegro          Podgorica   42.4411    19.2636
27             Netherlands          Amsterdam   52.3740     4.8897
28                  Norway               Oslo   59.9127    10.7461
29                  Poland             Warsaw   52.2298    21.0118
30                Portugal             Lisbon   38.7169    -9.1399
31                 Moldova           Chişinău   47.0056    28.8575
32                 Romania          Bucharest   44.4328    26.1043
33                  Russia             Moscow   55.7550    37.6218
34                  Serbia           Belgrade   44.8176    20.4633
35                Slovakia         Bratislava   48.1482    17.1067
36                Slovenia          Ljubljana   46.0511    14.5051
37                   Spain             Madrid   40.4165    -3.7026
38                  Sweden          Stockholm   59.3326    18.0649
39             Switzerland               Bern   46.9481     7.4474
40         North Macedonia             Skopje   42.0000    21.4333
41                 Türkiye             Ankara   39.9199    32.8543
42                 Ukraine               Kiev   50.4454    30.5186
43          United Kingdom             London   51.5085    -0.1257

### Add remaining values
Unfortunately, we'll have to manually add Kosovo.

In [129]:
city_coords.loc[-1] = ["Kosovo", "Pristina", 42.667542, 21.166191]
city_coords.index = city_coords.index + 1
city_coords = city_coords.sort_values(by="country")

In [130]:
city_coords

                   country       capital_city   latitude  longitude
1                  Albania             Tirana  41.327500  19.818900
2                  Armenia            Yerevan  40.182000  44.514600
3                  Austria             Vienna  48.206400  16.370700
4               Azerbaijan               Baku  40.377700  49.892000
5                  Belarus              Minsk  53.900000  27.566700
6                  Belgium  Bruxelles-Brussel  50.846700   4.349900
7   Bosnia and Herzegovina           Sarajevo  43.848600  18.356400
8                 Bulgaria              Sofia  42.697500  23.324200
9                  Croatia             Zagreb  45.814400  15.978000
10                  Cyprus            Nicosia  35.159500  33.366900
11                 Czechia             Prague  50.088000  14.420800
12                 Denmark         Copenhagen  55.675900  12.565500
13                 Estonia            Tallinn  59.437000  24.753500
14                 Finland           Helsinki  60.169200  24.940200
15                  France              Paris  48.853400   2.348800
16                 Georgia            Tbilisi  41.694100  44.833700
17                 Germany             Berlin  52.524400  13.410500
18                  Greece             Athens  37.953400  23.749000
19                 Hungary           Budapest  47.498000  19.039900
20                 Iceland          Reykjavík  64.135500 -21.895400
21                 Ireland             Dublin  53.333100  -6.248900
22                   Italy               Rome  41.894700  12.481100
0                   Kosovo           Pristina  42.667542  21.166191
23                  Latvia               Riga  56.946000  24.105900
24               Lithuania            Vilnius  54.689200  25.279800
25              Luxembourg         Luxembourg  49.611700   6.130000
26                   Malta           Valletta  35.899700  14.514700
32                 Moldova           Chişinău  47.005600  28.857500
27              Montenegro          Podgorica  42.441100  19.263600
28             Netherlands          Amsterdam  52.374000   4.889700
41         North Macedonia             Skopje  42.000000  21.433300
29                  Norway               Oslo  59.912700  10.746100
30                  Poland             Warsaw  52.229800  21.011800
31                Portugal             Lisbon  38.716900  -9.139900
33                 Romania          Bucharest  44.432800  26.104300
34                  Russia             Moscow  55.755000  37.621800
35                  Serbia           Belgrade  44.817600  20.463300
36                Slovakia         Bratislava  48.148200  17.106700
37                Slovenia          Ljubljana  46.051100  14.505100
38                   Spain             Madrid  40.416500  -3.702600
39                  Sweden          Stockholm  59.332600  18.064900
40             Switzerland               Bern  46.948100   7.447400
42                 Türkiye             Ankara  39.919900  32.854300
43                 Ukraine               Kiev  50.445400  30.518600
44          United Kingdom             London  51.508500  -0.125700

### Calculate the distance, in miles and km, between cities and Moscow
Let's start by creating two columns: `moscow_lat`, and `moscow_long`, with its coordinates. Then, we need to calculate the distance, in miles and km, between each city and Moscow.

In [131]:
city_coords["moscow_lat"] = city_coords.loc[city_coords["capital_city"] == "Moscow", "latitude"].values[0]
city_coords["moscow_long"] = city_coords.loc[city_coords["capital_city"] == "Moscow", "longitude"].values[0]

In [132]:
city_coords.head()

      country capital_city  latitude  longitude  moscow_lat  moscow_long
1     Albania       Tirana   41.3275    19.8189      55.755      37.6218
2     Armenia      Yerevan   40.1820    44.5146      55.755      37.6218
3     Austria       Vienna   48.2064    16.3707      55.755      37.6218
4  Azerbaijan         Baku   40.3777    49.8920      55.755      37.6218
5     Belarus        Minsk   53.9000    27.5667      55.755      37.6218

In [133]:
city_coords.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 1 to 44
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       45 non-null     object
 1   capital_city  45 non-null     object
 2   latitude      45 non-null     float64
 3   longitude     45 non-null     float64
 4   moscow_lat    45 non-null     float64
 5   moscow_long   45 non-null     float64
dtypes: float64(4), object(2)
memory usage: 2.5+ KB

In [134]:
def calculate_distance(row, unit):
    """
    Calculate the distance between Moscow and a city in either kilometers or miles.
    
    Args:
        row (pd.Series): A row of the DataFrame containing latitude and longitude.
        unit (str): The unit of distance, either "km" for kilometers or "mi" for miles.
    
    Returns:
        float: The distance in the specified unit.
    """
    coords_moscow = (row["moscow_lat"], row["moscow_long"])
    coords_city = (row["latitude"], row["longitude"])
    distance = geodesic(coords_moscow, coords_city)

    return distance.km if unit == "km" else distance.mi

city_coords["distance_km"] = city_coords.apply(calculate_distance, axis=1, unit="km")
city_coords["distance_mi"] = city_coords.apply(calculate_distance, axis=1, unit="mi")

In [135]:
city_coords

,country,capital_city,latitude,longitude,moscow_lat,moscow_long,distance_km,distance_mi
1,Albania,Tirana,41.327500,19.818900,55.755,37.6218,2061.505081,1280.959870
2,Armenia,Yerevan,40.182000,44.514600,55.755,37.6218,1804.240314,1121.102955
3,Austria,Vienna,48.206400,16.370700,55.755,37.6218,1674.501261,1040.486845
4,Azerbaijan,Baku,40.377700,49.892000,55.755,37.6218,1932.401811,1200.738817
5,Belarus,Minsk,53.900000,27.566700,55.755,37.6218,677.698516,421.102335
6,Belgium,Bruxelles-Brussel,50.846700,4.349900,55.755,37.6218,2260.638611,1404.695709
7,Bosnia and Herzegovina,Sarajevo,43.848600,18.356400,55.755,37.6218,1905.407170,1183.965125
8,Bulgaria,Sofia,42.697500,23.324200,55.755,37.6218,1779.443902,1105.695179
9,Croatia,Zagreb,45.814400,15.978000,55.755,37.6218,1871.837413,1163.105845
10,Cyprus,Nicosia,35.159500,33.366900,55.755,37.6218,2311.991102,1436.604668
11,Czechia,Prague,50.088000,14.420800,55.755,37.6218,1673.075362,1039.600832
12,Denmark,Copenhagen,55.675900,12.565500,55.755,37.6218,1566.217778,973.202608
13,Estonia,Tallinn,59.437000,24.753500,55.755,37.6218,869.927496,540.547885
14,Finland,Helsinki,60.169200,24.940200,55.755,37.6218,895.086147,556.180747
15,France,Paris,48.853400,2.348800,55.755,37.6218,2494.330387,1549.905047
16,Georgia,Tbilisi,41.694100,44.833700,55.755,37.6218,1649.031735,1024.660815
17,Germany,Berlin,52.524400,13.410500,55.755,37.6218,1613.743354,1002.733632
18,Greece,Athens,37.953400,23.749000,55.755,37.6218,2234.418684,1388.403402
19,Hungary,Budapest,47.498000,19.039900,55.755,37.6218,1572.955822,977.389434
20,Iceland,Reykjavík,64.135500,-21.895400,55.755,37.6218,3317.465664,2061.377595
21,Ireland,Dublin,53.333100,-6.248900,55.755,37.6218,2804.041794,1742.350793
22,Italy,Rome,41.894700,12.481100,55.755,37.6218,2381.276325,1479.656509
0,Kosovo,Pristina,42.667542,21.166191,55.755,37.6218,1875.848062,1165.597947
23,Latvia,Riga,56.946000,24.105900,55.755,37.6218,844.660695,524.847823
24,Lithuania,Vilnius,54.689200,25.279800,55.755,37.6218,793.263248,492.910930
25,Luxembourg,Luxembourg,49.611700,6.130000,55.755,37.6218,2214.455340,1375.998755
26,Malta,Valletta,35.899700,14.514700,55.755,37.6218,2817.032916,1750.423102
32,Moldova,Chişinău,47.005600,28.857500,55.755,37.6218,1146.860862,712.626301
27,Montenegro,Podgorica,42.441100,19.263600,55.755,37.6218,1985.028569,1233.439568
28,Netherlands,Amsterdam,52.374000,4.889700,55.755,37.6218,2154.869717,1338.973965
41,North Macedonia,Skopje,42.000000,21.433300,55.755,37.6218,1926.380663,1196.997449
29,Norway,Oslo,59.912700,10.746100,55.755,37.6218,1649.384427,1024.879968
30,Poland,Warsaw,52.229800,21.011800,55.755,37.6218,1154.482321,717.362056
31,Portugal,Lisbon,38.716900,-9.139900,55.755,37.6218,3915.117069,2432.740961
33,Romania,Bucharest,44.432800,26.104300,55.755,37.6218,1500.717511,932.502629
34,Russia,Moscow,55.755000,37.621800,55.755,37.6218,0.000000,0.000000
35,Serbia,Belgrade,44.817600,20.463300,55.755,37.6218,1715.978681,1066.259719
36,Slovakia,Bratislava,48.148200,17.106700,55.755,37.6218,1635.635091,1016.336526
37,Slovenia,Ljubljana,46.051100,14.505100,55.755,37.6218,1937.242352,1203.746590
38,Spain,Madrid,40.416500,-3.702600,55.755,37.6218,3448.195009,2142.609044
39,Sweden,Stockholm,59.332600,18.064900,55.755,37.6218,1231.689760,765.336535
40,Switzerland,Bern,46.948100,7.447400,55.755,37.6218,2294.991494,1426.041601
42,Türkiye,Ankara,39.919900,32.854300,55.755,37.6218,1795.387453,1115.602042
43,Ukraine,Kiev,50.445400,30.518600,55.755,37.6218,757.836072,470.897504
44,United Kingdom,London,51.508500,-0.125700,55.755,37.6218,2508.674067,1558.817796

## Combine both datasets
It is time now to merge both datasets!

In [136]:
merged_table = sipri_joined_table.merge(
    right=city_coords,
    how="inner",
    on="country"
)

In [137]:
merged_table

,country,year,military_expenditures_usd_2022,military_expenditures_current_usd,share_GDP,share_govt,capital_city,latitude,longitude,moscow_lat,moscow_long,distance_km,distance_mi
0,Albania,1993,1.772197e+08,3.928984e+07,0.031995,NaN,Tirana,41.3275,19.8189,55.755,37.6218,2061.505081,1280.959870
1,Albania,1994,1.694002e+08,4.964950e+07,0.025478,NaN,Tirana,41.3275,19.8189,55.755,37.6218,2061.505081,1280.959870
2,Albania,1995,1.578554e+08,5.090752e+07,0.020536,NaN,Tirana,41.3275,19.8189,55.755,37.6218,2061.505081,1280.959870
3,Albania,1996,1.417564e+08,4.571336e+07,0.013790,NaN,Tirana,41.3275,19.8189,55.755,37.6218,2061.505081,1280.959870
4,Albania,1997,9.897513e+07,2.982549e+07,0.012831,0.044247,Tirana,41.3275,19.8189,55.755,37.6218,2061.505081,1280.959870
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,United Kingdom,2020,6.672282e+10,5.833237e+10,0.021630,0.043299,London,51.5085,-0.1257,55.755,37.6218,2508.674067,1558.817796
1404,United Kingdom,2021,6.774978e+10,6.514860e+10,0.020724,0.045193,London,51.5085,-0.1257,55.755,37.6218,2508.674067,1558.817796
1405,United Kingdom,2022,6.887828e+10,6.406988e+10,0.020569,0.046682,London,51.5085,-0.1257,55.755,37.6218,2508.674067,1558.817796
1406,United Kingdom,2023,7.530339e+10,7.530339e+10,0.022306,0.050499,London,51.5085,-0.1257,55.755,37.6218,2508.674067,1558.817796
1407,United Kingdom,2024,7.738996e+10,8.176317e+10,0.022786,0.052527,London,51.5085,-0.1257,55.755,37.6218,2508.674067,1558.817796

# Export the final dataset
Finally! We can export the table as `output`!

In [138]:
merged_table.to_csv(f"{transformed_data}military_expenditures_final.csv", index=False, sep=',')

# Extra – Convert to Hyper using API
As an extra, let's try to use the `tableahyperapi` library to automatically generate a `.hyper` extract for our data.

In [139]:
def run_create_hyper_file_from_dataframe(df, path):
    """
    Load data from a pandas DataFrame into a new Hyper file.
    """

    print("Example – Load data from pandas DataFrame in new Hyper file")

    # 1. Load DataFrame
    data = df
    # 2. Define path where Hyper file will be saved
    path_to_database = path

    # 3. Optional process parameters.
    # These settings limit the number of log files and their size.
    process_parameters = {
        "log_file_max_count": "2", # Limit the number of log files to 2
        "log_file_size_limit": "100M" # Limit the log size to 100mb
    }

    # 4. Start the Hyper Process
    # Telemetry is set to sed usage data to Tableau
    with HyperProcess(
        telemetry=Telemetry.SEND_USAGE_DATA_TO_TABLEAU, parameters=process_parameters
    ) as hyper:
        
        # 5: Optional connection parameters
        # This sets the locale for the time formats to "en_US"
        connection_parameters = {"lc_time": "en_US"}

        # 6: Create a connection to the Hyper file.
        # If the file exists, it will be replaced.
        with Connection(
            endpoint=hyper.endpoint,
            database=path_to_database,
            create_mode=CreateMode.CREATE_AND_REPLACE,
            parameters=connection_parameters,
        ) as connection:
            
            # 7. Define the table schema
            table = TableDefinition(
                table_name="Europe Military Expenditures", # Table name
                columns= [
                    TableDefinition.Column(
                        "country", SqlType.text(), NOT_NULLABLE
                    ),
                    TableDefinition.Column(
                        "year", SqlType.int(), NOT_NULLABLE
                    ),
                    TableDefinition.Column(
                        "military_expenditures_usd_2022", SqlType.double()
                    ),
                    TableDefinition.Column(
                        "military_expenditures_current_usd", SqlType.double()
                    ),
                    TableDefinition.Column(
                        "share_GDP", SqlType.double()
                    ),
                                        TableDefinition.Column(
                        "share_govt", SqlType.double()
                    ),
                    TableDefinition.Column(
                        "capital_city", SqlType.text()
                    ),                    
                    TableDefinition.Column(
                        "latitude", SqlType.double()
                    ),
                    TableDefinition.Column(
                        "longitude", SqlType.double()
                    ),
                    TableDefinition.Column(
                        "moscow_lat", SqlType.double()
                    ),
                    TableDefinition.Column(
                        "moscow_long", SqlType.double()
                    ),
                    TableDefinition.Column(
                        "distance_km", SqlType.double()
                    ),
                    TableDefinition.Column(
                        "distance_mi", SqlType.double()
                    ),  
                ]
            )
            
            # 8. Create the table in the hyper file
            connection.catalog.create_table(table_definition=table)

            # 9. Use the Inserter to insert data into the table.
            with Inserter(connection, table) as inserter:
                # Iterate over the DataFrame rows as tuples.
                # `itertuples` returns an iterator yielding named tuples.
                for row in df.itertuples(index=False, name=None):
                    inserter.add_row(row) # Add each row to the inserter
                inserter.execute() # Execute the insertion into the Hyper file
            
            # 10. Verify the number of rows inserted.
            row_count = connection.execute_scalar_query(
                f"SELECT COUNT(*) FROM {table.table_name}"
            )

            print(
                f"The number of rows in table {table.table_name} is {row_count}"
            )

            print("Data has been successfully inserted into the Hyper file.")
        
        # The connection is automatically closed when exiting the 'with' block.
        print("The connection to the Hyper file has been closed.")

    # The Hyper process is automatically shut down when exiting the 'with' block.
    print("The Hyper process has been shut down")

In [140]:
run_create_hyper_file_from_dataframe(df=merged_table, path=f"{refined_data}european_military_expenditures.hyper")

Example – Load data from pandas DataFrame in new Hyper file
The number of rows in table "Europe Military Expenditures" is 1408
Data has been successfully inserted into the Hyper file.
The connection to the Hyper file has been closed.
The Hyper process has been shut down

Great! Our dataset has been successfully inserted into a Hyper file, which can be directly consumed in Tableau!

# Conclusion
Wow, we went through a lot! We've managed to:
- Import our data
- Clean, pivot, and enrich our data
- Store it as a `.csv` file
- Convert it to a `.hyper` file to be used in Tableau

Our following challenges would involve creating a script for this process (which we'll do separately). For now, we move on to the analysis step! Thank you for following me so far!